name: Build and Release

on:
  push:
    tags:
      - "v*" # 当推送带 v 开头的标签时触发，比如 v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'
      
      - name: Get dependencies
        run: flutter pub get
        
      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --release
        
      - name: Compress web build
        run: cd build/web && zip -r ../../web-build.zip .
        
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            web-build.zip
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 